apiVersion: apps/v1
kind: Deployment
metadata:
  name: cash-service
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cash-service
  template:
    metadata:
      labels:
        app: cash-service
    spec:
      containers:
        - name: cash-service
          image: ghcr.io/sik2/msa-k8s:cash-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "redpanda:29092"
          envFrom:
            - secretRef:
                name: app-secret
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            periodSeconds: 15
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: cash-service
  namespace: backend
spec:
  selector:
    app: cash-service
  ports:
    - port: 8083
      targetPort: 8083
