apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: backend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - api.ondanyang.com
      secretName: api-ondanyang-tls
  rules:
    - host: api.ondanyang.com
      http:
        paths:
          - path: /api/v1/member
            pathType: Prefix
            backend:
              service:
                name: member-service
                port:
                  number: 8080
          - path: /api/v1/post
            pathType: Prefix
            backend:
              service:
                name: post-service
                port:
                  number: 8081
          - path: /api/v1/market
            pathType: Prefix
            backend:
              service:
                name: market-service
                port:
                  number: 8084
          - path: /api/v1/cash
            pathType: Prefix
            backend:
              service:
                name: cash-service
                port:
                  number: 8083
          - path: /api/v1/payout
            pathType: Prefix
            backend:
              service:
                name: payout-service
                port:
                  number: 8082
