apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: backend
type: Opaque
stringData:
  JWT_SECRET_KEY: "abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789"
  SYSTEM_API_KEY: "system-api-key-for-internal-service-communication"
  TOSS_PAYMENTS_SECRET_KEY: "NEED_TO_INPUT"
  MYSQL_PASSWORD: "root123414"
